### ISSUE TITLE
Add release timebox to filter

### ISSUE THREAD

**Issue by Echo3ToEcho7** [sficarrotta/WSJF_Grid#2]
Customer request

**Comment by sficarrotta** [comment]
The latest version does have a release time box - check it out & give me some feedback :)

**Comment by RallyRonnie** [comment]
Thanks. I used your "ignore release" code to modify the release-team-status.

**Comment by sficarrotta** [comment]
kewl!

On Mon, Apr 6, 2015 at 2:58 PM, Ronnie notifications@github.com wrote:

> Thanks. I used your "ignore release" code to modify the
> release-team-status.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sficarrotta/WSJF_Grid/issues/2#issuecomment-90198123.

## 

_Summer Ficarrotta_\* Solutions Architect*_, Rally Software_
Tel: (719) 964-2317
www.rallydev.com

https://www.google.com/url?q=https%3A%2F%2Fwww.rallydev.com%2Frallyon%2Frallyon2015%3Futm_source%3Drally_mktg%26utm_medium%3Dsignature%26utm_content%3Dmar2015%26utm_campaign%3Drallyon15&sa=D&sntz=1&usg=AFQjCNEqGya5WbmI780kQXOdAAYL91TPrA

https://www.google.com/url?q=https%3A%2F%2Fwww.rallydev.com%2Frallyon%2Frallyon2015%3Futm_source%3Drally_mktg%26utm_medium%3Dsignature%26utm_content%3Dmar2015%26utm_campaign%3Drallyon15&sa=D&sntz=1&usg=AFQjCNEqGya5WbmI780kQXOdAAYL91TPrA

Get New Teams Up and Running Quickly with Rally TeamStart Live complementary
Webinars every Tuesday.  http://forms.rallydev.com/teamstartregistration

Join the conversation in the Rally Success Community
https://success.rallydev.com.

http://www.scrumalliance.org/pages/CSM
http://www.linkedin.com/in/sficarrotta
